### ISSUE TITLE
framework.js:1 Uncaught DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

### ISSUE THREAD

**Issue by santoshgistto** [sleepy-zone/fabritor-web#47]
```
framework.js:1 Uncaught DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.
    at Object.toDataURL (https://fabritor.surge.sh/js/43ea133b.js:1:12229)
    at i.toDataURL (https://fabritor.surge.sh/js/43ea133b.js:1:134528)
    at e.value (https://fabritor.surge.sh/js/p_index.js:1:137630)
    at onClick (https://fabritor.surge.sh/js/p_index.js:1:20678)
    at Object.<anonymous> (https://fabritor.surge.sh/js/675.js:1:179858)
    at https://fabritor.surge.sh/js/675.js:1:810743
    at Object.<anonymous> (https://fabritor.surge.sh/js/675.js:1:784160)
    at https://fabritor.surge.sh/js/675.js:1:767597
    at onClick (https://fabritor.surge.sh/js/675.js:1:770355)
    at Object.ej (https://fabritor.surge.sh/js/framework.js:1:78449)
```

**Comment by sleepy-zone** [comment]
I think u have imported an image, but the image does not support cross-origin.
